import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBarLayout from "./components/navbarlayout";
import FooterLayout from "./components/footerlayout";
import { Providers } from "./GlobalRedux/provider";
import { store } from "./GlobalRedux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cre Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Providers store={store}>{children}</Providers>
      </body>
    </html>
  );
}
